### ISSUE TITLE
Failed to resolve 'hiwi-test-kafka-1:29092'

### ISSUE THREAD

**Issue by aakarsh1011** [densalzmann/hiwi-test#1]
After installation of mentioned packages and starting the docker container using `docker-compose up` and creating the descriptors, I was able to access the kafdrop at the `localhost:9000`, however I was assuming after the mentioned step the datasource is then proccessed to an kafka-server` (hiwi-test-kafka-1:29092)` and I would be able to view the data on the kafdrop under `location_topic`. However I am continuously getting this error :

`datasupplier-1  | %3|1706977717.710|FAIL|rdkafka#producer-1| [thrd:hiwi-test-kafka-1:29092/bootstrap]: hiwi-test-kafka-1:29092/bootstrap: Failed to resolve 'hiwi-test-kafka-1:29092': Name or 
service not known (after 1899ms in state CONNECT, 10 identical error(s) suppressed)`

I am not sure if we have to edit something in the producer side or make changes in the `main.py` file for this?

**Comment by densalzmann** [comment]
First of all you need to check if the kafka server is processing as expected. You may look at the logs of the kafka-broker container.  However, assuming that  kafdrop is connecting to kafka-broker, the broker should have opened the 29092 which the supplier and kafdrop are using.

What could be the possible fix:
- try using `kafka:29092` instead of `hiwi-test-kafka-1:29092` in `src/main.py:18` and rebuild the datasupplier container with: `$ docker compose down; docker compose up -d --build`.
- try using the external port `kafka:9092` in `src/main.py:18` and rebuild the datasupplier.
- if nothing works; please try attach into the datasupplier container and use "ping kafka" for debugging the docker name space.
Please, give here a feedback, if this will help.

**Comment by aakarsh1011** [comment]
Yes, I implemented the first fix already, just wanted to know if I should change the `src/main.py`. thank you
